# Generated by Django 4.2.16 on 2024-12-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order_orderitem_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Success", "Success")],
                default="Pending",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.customer"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_datetime",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="mfg_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
