# Generated by Django 4.2.16 on 2024-12-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
    ]
