# Generated by Django 4.2.16 on 2024-12-07 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_payment_paid_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="shop.user",
            ),
        ),
    ]
