# Generated by Django 4.2.16 on 2024-12-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_payment_paid_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="paid_by",
            new_name="customer",
        ),
    ]
