# Generated by Django 4.2.16 on 2024-12-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_payment_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="customer",
            new_name="paid_by",
        ),
    ]
