# Generated by Django 4.2.16 on 2024-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_rename_customer_payment_paid_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=10),
        ),
    ]
